services:
    jekyll:
        image: vinayak1998th/resume-container:npm 
        container_name: blog-run
        command: >
            -c "bundle exec jekyll serve --drafts --watch --force_polling --host 0.0.0.0"
        ports:
            - 4000:4000
            - 35729:35729
        volumes:
            - .:/site
        environment:
            - JEKYLL_ENV=development